### ISSUE TITLE
undefined method 'source' when running `bundle exec middleman build`

### ISSUE THREAD

**Issue by michaelparenteau** [middleman/middleman-sprockets#109]
I am using Ruby 2.3.0, middleman command is working.. built prototype and dev environment is great. Now am looking to build static package.. and stuff is blowing up. Any ideas here?

My Gemfile:
```
source 'https://rubygems.org'

# Middleman Gems
gem 'middleman', '>= 4.0.0'
gem "middleman-sprockets", "~> 4.0.0.rc"
gem 'middleman-livereload'
gem 'middleman-compass', '>= 4.0.0'
gem 'susy', '~> 2.2.11'
gem 'breakpoint', '~> 2.5.0'
gem 'middleman-syntax', '~> 2.1.0'
gem 'middleman-jquery'
gem "faker", "~> 1.6.3"
gem 'font-awesome-middleman'

```

In config.rb

```
###
# Compass
###
compass_config do |config|
  require 'breakpoint'
  config.output_style = :compact
end

activate :directory_indexes

# Extensions

# https://github.com/middleman/middleman-syntax
activate :syntax, line_numbers: true

set :markdown_engine, :kramdown
set :markdown, :fenced_code_blocks => true, :smartypants => true

# General configuration
set :css_dir, 'stylesheets'
set :js_dir, 'javascripts'
set :images_dir, 'images'

# Reload the browser automatically whenever files change
configure :development do
  activate :livereload
end

# Build-specific configuration
configure :build do
  #activate :minify_css
  #activate :minify_javascript
  #activate :gzip
end
```

Here is the stacktrace:

```
/Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-sprockets-4.0.0.rc.1/lib/middleman-sprockets/extension.rb:235:in `initialize': undefined method `source' for nil:NilClass (NoMethodError)
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-sprockets-4.0.0.rc.1/lib/middleman-sprockets/extension.rb:120:in `new'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-sprockets-4.0.0.rc.1/lib/middleman-sprockets/extension.rb:120:in `generate_resource'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-sprockets-4.0.0.rc.1/lib/middleman-sprockets/extension.rb:97:in `block in manipulate_resource_list'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-sprockets-4.0.0.rc.1/lib/middleman-sprockets/extension.rb:90:in `each'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-sprockets-4.0.0.rc.1/lib/middleman-sprockets/extension.rb:90:in `reduce'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-sprockets-4.0.0.rc.1/lib/middleman-sprockets/extension.rb:90:in `manipulate_resource_list'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.6/lib/middleman-core/sitemap/store.rb:234:in `block (4 levels) in ensure_resource_list_updated!'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.6/lib/middleman-core/util.rb:21:in `instrument'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.6/lib/middleman-core/sitemap/store.rb:232:in `block (3 levels) in ensure_resource_list_updated!'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.6/lib/middleman-core/sitemap/store.rb:231:in `block (2 levels) in ensure_resource_list_updated!'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.6/lib/middleman-core/util.rb:21:in `instrument'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.6/lib/middleman-core/sitemap/store.rb:224:in `block in ensure_resource_list_updated!'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.6/lib/middleman-core/sitemap/store.rb:221:in `ensure_resource_list_updated!'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.6/lib/middleman-core/sitemap/extensions/on_disk.rb:21:in `ready'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.6/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.6/lib/middleman-core/callback_manager.rb:57:in `block in execute'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.6/lib/middleman-core/callback_manager.rb:57:in `execute'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.6/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.6/lib/middleman-core/application.rb:307:in `initialize'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.6/lib/middleman-cli/build.rb:63:in `new'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.6/lib/middleman-cli/build.rb:63:in `block in build'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.6/lib/middleman-core/util.rb:21:in `instrument'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.6/lib/middleman-cli/build.rb:62:in `build'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/om/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.6/bin/middleman:67:in `<top (required)>'
	from /Users/om/.rbenv/versions/2.3.0/bin/middleman:23:in `load'
	from /Users/om/.rbenv/versions/2.3.0/bin/middleman:23:in `<main>'
```

**Comment by stevenosloan** [comment]
@michaelparenteau can you try off of master? there's been a lot of changes made since then -- if it's still blowing up, run it with `--verbose` and there should be some lines that start with `== Sprockets` that'll give a bit more info for debugging.


To run off master:
```ruby
# Gemfile
#...
gem 'middleman-sprockets', github: 'middleman/middleman-sprockets'
#...
```

You'll also need to add `activate :sprockets` to your `config.rb`

**Comment by michaelparenteau** [comment]
@stevenosloan YES. Using master worked.

Thank you :)
