### ISSUE TITLE
middleman-sprockets version 4.X unable to build css

### ISSUE THREAD

**Issue by asifrafiq** [middleman/middleman-sprockets#133]
## Steps to reproduce the problem
- My project repo: [this repo](https://github.com/umerebryx/upcase-middleman-sample)
- Install the bundle from Gemfile and then `middleman build` in root directory of the project

**Error on build setup**

```
Traceback (most recent call last):
        66: from /usr/local/bin/middleman:23:in `<main>'
        65: from /usr/local/bin/middleman:23:in `load'
        64: from /usr/local/lib/ruby/gems/2.5.0/gems/middleman-core-3.4.1/bin/middleman:18:in `<top (required)>'
        63: from /usr/local/lib/ruby/gems/2.5.0/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:20:in `start'
        62: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        61: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        60: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        59: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:128:in `run'
        58: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:29:in `run'
        57: from /usr/local/lib/ruby/gems/2.5.0/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:72:in `method_missing'
        56: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        55: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        54: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        53: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        52: from /usr/local/lib/ruby/gems/2.5.0/gems/middleman-core-3.4.1/lib/middleman-core/cli/build.rb:62:in `build'
        51: from /usr/local/lib/ruby/gems/2.5.0/gems/middleman-core-3.4.1/lib/middleman-core/cli/build.rb:95:in `shared_instance'
        50: from /usr/local/lib/ruby/gems/2.5.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/request.rb:57:in `inst'
        49: from /usr/local/lib/ruby/gems/2.5.0/gems/hooks-0.4.1/lib/hooks/instance_hooks.rb:6:in `run_hook'
        48: from /usr/local/lib/ruby/gems/2.5.0/gems/hooks-0.4.1/lib/hooks.rb:55:in `run_hook_for'
        47: from /usr/local/lib/ruby/gems/2.5.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `run'
        46: from /usr/local/lib/ruby/gems/2.5.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `inject'
        45: from /usr/local/lib/ruby/gems/2.5.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `each'
        44: from /usr/local/lib/ruby/gems/2.5.0/gems/hooks-0.4.1/lib/hooks/hook.rb:40:in `block in run'
        43: from /usr/local/lib/ruby/gems/2.5.0/gems/hooks-0.4.1/lib/hooks/hook.rb:55:in `execute_callback'
        42: from /usr/local/lib/ruby/gems/2.5.0/gems/hooks-0.4.1/lib/hooks/hook.rb:59:in `evaluate_callback'
        41: from /usr/local/lib/ruby/gems/2.5.0/gems/uber-0.0.15/lib/uber/options.rb:60:in `call'
        40: from /usr/local/lib/ruby/gems/2.5.0/gems/uber-0.0.15/lib/uber/options.rb:82:in `evaluate_for'
        39: from /usr/local/lib/ruby/gems/2.5.0/gems/uber-0.0.15/lib/uber/options.rb:96:in `proc!'
        38: from /usr/local/lib/ruby/gems/2.5.0/gems/uber-0.0.15/lib/uber/options.rb:96:in `instance_exec'
        37: from /usr/local/lib/ruby/gems/2.5.0/gems/middleman-core-3.4.1/lib/middleman-core/sitemap/extensions/on_disk.rb:31:in `block in initialize'
        36: from /usr/local/lib/ruby/gems/2.5.0/gems/middleman-core-3.4.1/lib/middleman-core/sitemap/store.rb:208:in `ensure_resource_list_updated!'
        35: from /usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
        34: from /usr/local/lib/ruby/gems/2.5.0/gems/middleman-core-3.4.1/lib/middleman-core/sitemap/store.rb:216:in `block in ensure_resource_list_updated!'
        33: from /usr/local/lib/ruby/gems/2.5.0/gems/middleman-core-3.4.1/lib/middleman-core/sitemap/store.rb:216:in `each'
        32: from /usr/local/lib/ruby/gems/2.5.0/gems/middleman-core-3.4.1/lib/middleman-core/sitemap/store.rb:217:in `block (2 levels) in ensure_resource_list_updated!'
        31: from /usr/local/lib/ruby/gems/2.5.0/gems/middleman-core-3.4.1/lib/middleman-more/extensions/asset_hash.rb:38:in `manipulate_resource_list'
        30: from /usr/local/lib/ruby/gems/2.5.0/gems/middleman-core-3.4.1/lib/middleman-more/extensions/asset_hash.rb:38:in `each'
        29: from /usr/local/lib/ruby/gems/2.5.0/gems/middleman-core-3.4.1/lib/middleman-more/extensions/asset_hash.rb:47:in `manipulate_single_resource'
        28: from /usr/local/lib/ruby/gems/2.5.0/gems/rack-test-1.1.0/lib/rack/test.rb:58:in `get'
        27: from /usr/local/lib/ruby/gems/2.5.0/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
        26: from /usr/local/lib/ruby/gems/2.5.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
        25: from /usr/local/lib/ruby/gems/2.5.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
        24: from /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.11/lib/rack/builder.rb:153:in `call'
        23: from /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.11/lib/rack/lint.rb:37:in `call'
        22: from /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.11/lib/rack/lint.rb:49:in `_call'
        21: from /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.11/lib/rack/head.rb:13:in `call'
        20: from /usr/local/lib/ruby/gems/2.5.0/gems/middleman-core-3.4.1/lib/middleman-more/extensions/minify_css.rb:62:in `call'
        19: from /usr/local/lib/ruby/gems/2.5.0/gems/middleman-core-3.4.1/lib/middleman-more/extensions/minify_css.rb:100:in `minify'
        18: from /usr/local/lib/ruby/gems/2.5.0/gems/middleman-core-3.4.1/lib/middleman-more/extensions/minify_css.rb:28:in `compress'
        17: from /usr/local/lib/ruby/gems/2.5.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:41:in `parse'
        16: from /usr/local/lib/ruby/gems/2.5.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:125:in `stylesheet'
        15: from /usr/local/lib/ruby/gems/2.5.0/gems/sass-3.4.25/lib/sass/scss/css_parser.rb:21:in `block_contents'
        14: from /usr/local/lib/ruby/gems/2.5.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:674:in `block_contents'
        13: from /usr/local/lib/ruby/gems/2.5.0/gems/sass-3.4.25/lib/sass/scss/css_parser.rb:29:in `block_child'
        12: from /usr/local/lib/ruby/gems/2.5.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:205:in `directive'
        11: from /usr/local/lib/ruby/gems/2.5.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:213:in `directive_body'
        10: from /usr/local/lib/ruby/gems/2.5.0/gems/sass-3.4.25/lib/sass/scss/css_parser.rb:21:in `block_contents'
         9: from /usr/local/lib/ruby/gems/2.5.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:677:in `block_contents'
         8: from /usr/local/lib/ruby/gems/2.5.0/gems/sass-3.4.25/lib/sass/scss/css_parser.rb:31:in `block_child'
         7: from /usr/local/lib/ruby/gems/2.5.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:720:in `declaration_or_ruleset'
         6: from /usr/local/lib/ruby/gems/2.5.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:791:in `try_declaration'
         5: from /usr/local/lib/ruby/gems/2.5.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:1183:in `rethrow'
         4: from /usr/local/lib/ruby/gems/2.5.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:786:in `block in try_declaration'
         3: from /usr/local/lib/ruby/gems/2.5.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:1132:in `tok!'
         2: from /usr/local/lib/ruby/gems/2.5.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:1137:in `expected'
         1: from /usr/local/lib/ruby/gems/2.5.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:1207:in `expected'
(sass):20: Invalid CSS after "...AAAAABADJGT3c=)": expected ";", was ")))))))))))); f..." (Sass::SyntaxError)

```
*Gemfile*, *config.rb* and *error log* file (from `middleman build` command) are attached 
[error log.txt](https://github.com/middleman/middleman-sprockets/files/3540698/error.log.txt)
[Gemfile.txt](https://github.com/middleman/middleman-sprockets/files/3540704/Gemfile.txt)
[config.rb.txt](https://github.com/middleman/middleman-sprockets/files/3540705/config.rb.txt)
[2BC6BB4F7F64E1234.css.txt](https://github.com/middleman/middleman-sprockets/files/3540769/2BC6BB4F7F64E1234.css.txt)

Whereas those css are working fine with sprockets version 3.X

## Development environment 
- Ruby version: 2.5.3
- Middleman version: 4.3.5
- Middleman Sprockets version: 4.1.1
- OS version: CentOS Linux 7 (Core)

**Comment by tdreyno** [comment]
The error above shows that the Middleman version in use is `middleman-core-3.4.1`, not `4.3.5` as the the env above says.
