### ISSUE TITLE
Sprockets::FileNotFound error

### ISSUE THREAD

**Issue by bcackerman** [middleman/middleman-sprockets#75]
I'm running bundle `bundle exec middleman build` and continually get this error using `middleman (3.3.7)`
```
/Users/Ackerman/.rvm/gems/ruby-2.0.0-p353@global/gems/sprockets-2.12.3/lib/sprockets/base.rb:153:in `resolve': couldn't find file 'Amount homepage/html/source/images/banner-bg@2x.jpg' (Sprockets::FileNotFound)
```
I've tried everything possible, the image is definitely there as well.  I'm referencing it in a SCSS file using `background-image: image-url("banner-bg@2x.jpg")` could it be a bug?

**Comment by tdreyno** [comment]
what is `Amount homepage/html/source/images/banner-bg@2x.jpg`?

Seems like you may have some kind of parse error which is adding extra content to the name of the file being passed to middleman?

**Comment by rmhsilva** [comment]
On a fresh init of middleman, I am getting the following error, which is possibly related.


>/Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:153:in `resolve': couldn't find file '/Users/xxx/Documents/Projects/new-middleman-test/source/images/background.png' (Sprockets::FileNotFound)


Ruby 2.2.0,
Gems included by the bundle:
```
  * activesupport (4.1.9)
  * addressable (2.3.7)
  * bundler (1.7.12)
  * celluloid (0.16.0)
  * chunky_png (1.3.3)
  * coffee-script (2.3.0)
  * coffee-script-source (1.9.0)
  * compass (1.0.3)
  * compass-core (1.0.3)
  * compass-import-once (1.0.5)
  * em-websocket (0.5.1)
  * erubis (2.7.0)
  * eventmachine (1.0.6)
  * execjs (2.3.0)
  * ffi (1.9.6)
  * haml (4.0.6)
  * hike (1.2.3)
  * hitimes (1.2.2)
  * hooks (0.4.0)
  * http_parser.rb (0.6.0)
  * i18n (0.6.11)
  * json (1.8.2)
  * kramdown (1.5.0)
  * listen (2.8.5)
  * middleman (3.3.7)
  * middleman-blog (3.5.3)
  * middleman-core (3.3.7)
  * middleman-livereload (3.1.1)
  * middleman-sprockets (3.4.1)
  * minitest (5.5.1)
  * multi_json (1.10.1)
  * padrino-helpers (0.12.4)
  * padrino-support (0.12.4)
  * rack (1.6.0)
  * rack-livereload (0.3.15)
  * rack-test (0.6.3)
  * rb-fsevent (0.9.4)
  * rb-inotify (0.9.5)
  * sass (3.4.11)
  * sprockets (2.12.3)
  * sprockets-helpers (1.1.0)
  * sprockets-sass (1.3.1)
  * thor (0.19.1)
  * thread_safe (0.3.4)
  * tilt (1.4.1)
  * timers (4.0.1)
  * tzinfo (1.2.2)
  * uber (0.0.13)
  * uglifier (2.7.0)
```

**Comment by tdreyno** [comment]
Does the file `/Users/xxx/Documents/Projects/new-middleman-test/source/images/background.png` exist?

**Comment by rmhsilva** [comment]
Yes - it is created by the standard middleman init command (running `middleman init new-middleman-test`)

**Comment by bcackerman** [comment]
Yes, my file exists as well

**Comment by bcackerman** [comment]
I figured out the problem for me.  When I moved my directory to `/Users/Ackerman/Downloads/html` it worked fine.  It seems the problem is `sprockets-2.12.3/lib/sprockets/base.rb:153` couldn't determine the path when there was parentheses and spaces in it.

**Comment by tdreyno** [comment]
Nice catch @bcackerman. Sounds like maybe an upstream Sprockets issue, we'll take a look

**Comment by bpainter** [comment]
Definitely a good catch @bcackerman. Upgraded today and started having the same issue. Renamed a folder with parentheses in the name and Sprockets started working again.

**Comment by tdreyno** [comment]
I'm going to try and figure out if this is Sprockets' bug or ours

**Comment by mofirouz** [comment]
I'm getting the same error. 
```
mo~/Desktop/www (master):middleman server
WARN: Unresolved specs during Gem::Specification.reset:
      rack (< 2.0, >= 1.4.5)
      uber (~> 0.0.4)
      rack-test (~> 0.6.2)
      thor (< 2.0, >= 0.15.2)
      activesupport (~> 4.1.0)
      padrino-helpers (~> 0.12.3)
      listen (< 3.0, >= 2.7.9)
      i18n (~> 0.6.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
== The Middleman is loading
/Library/Ruby/Gems/2.0.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:153:in `resolve': couldn't find file 'uri.js/src/URI.min.js' (Sprockets::FileNotFound)
	from /Library/Ruby/Gems/2.0.0/gems/middleman-sprockets-3.3.10/lib/middleman-sprockets/imported_asset.rb:29:in `resolve_path_with'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-sprockets-3.3.10/lib/middleman-sprockets/extension.rb:79:in `block in manipulate_resource_list'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-sprockets-3.3.10/lib/middleman-sprockets/extension.rb:78:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-sprockets-3.3.10/lib/middleman-sprockets/extension.rb:78:in `manipulate_resource_list'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.7/lib/middleman-core/sitemap/store.rb:215:in `block (2 levels) in ensure_resource_list_updated!'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.7/lib/middleman-core/sitemap/store.rb:214:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.7/lib/middleman-core/sitemap/store.rb:214:in `reduce'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.7/lib/middleman-core/sitemap/store.rb:214:in `block in ensure_resource_list_updated!'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.7/lib/middleman-core/sitemap/store.rb:208:in `ensure_resource_list_updated!'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.7/lib/middleman-core/sitemap/extensions/on_disk.rb:31:in `block in initialize'
	from /Library/Ruby/Gems/2.0.0/gems/uber-0.0.13/lib/uber/options.rb:80:in `instance_exec'
	from /Library/Ruby/Gems/2.0.0/gems/uber-0.0.13/lib/uber/options.rb:80:in `proc!'
	from /Library/Ruby/Gems/2.0.0/gems/uber-0.0.13/lib/uber/options.rb:69:in `evaluate_for'
	from /Library/Ruby/Gems/2.0.0/gems/uber-0.0.13/lib/uber/options.rb:60:in `evaluate'
	from /Library/Ruby/Gems/2.0.0/gems/hooks-0.4.0/lib/hooks/hook.rb:53:in `execute_callback'
	from /Library/Ruby/Gems/2.0.0/gems/hooks-0.4.0/lib/hooks/hook.rb:40:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `inject'
	from /Library/Ruby/Gems/2.0.0/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/hooks-0.4.0/lib/hooks.rb:55:in `run_hook_for'
	from /Library/Ruby/Gems/2.0.0/gems/hooks-0.4.0/lib/hooks/instance_hooks.rb:6:in `run_hook'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.7/lib/middleman-core/core_extensions/request.rb:50:in `inst'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.7/lib/middleman-core/preview_server.rb:103:in `new_app'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.7/lib/middleman-core/preview_server.rb:21:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.7/lib/middleman-core/cli/server.rb:78:in `server'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.7/lib/middleman-core/cli.rb:72:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.7/lib/middleman-core/cli.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.7/bin/middleman:18:in `<top (required)>'
	from /usr/bin/middleman:23:in `load'
	from /usr/bin/middleman:23:in `<main>'
```

**Comment by Arcovion** [comment]
@mofirouz See https://github.com/sstephenson/sprockets/issues/706

**Comment by mofirouz** [comment]
@Arcovion  Thanks! That helped :)

**Comment by tdreyno** [comment]
Okay, closing this in favor of that.

**Comment by komor72** [comment]
Just checking if the correct bug has been identified – I’ve stumbled on the same problem today, after upgrading a project from MM 3.3.5 to 3.3.10. My problematic path was `/Prace_WWW/D+K/www-website/source/site_images/404.jpg` (notice the plus sign in the folder name). After removing plus sign all is working again, both development server and build.

**Comment by bpainter** [comment]
@komor72 Issue looks to be an issue with the Sprockets gem. https://github.com/sstephenson/sprockets/issues/706

I upgraded to MM 3.3.10 and started getting the following sprockets error similar to @bcackerman:

```
== The Middleman is loading
/Users/bermonpainter/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:153:in `resolve': couldn't find file '/Users/bermonpainter/Dropbox (Personal)/Sites/blendconf.com/blendconf-site/source/assets/images/content/blend-conf-icon.png' (Sprockets::FileNotFound)
```

I tried to update sprockets 3.0.0.beta.8 based on https://github.com/sstephenson/sprockets/issues/706 but got:

```
You have requested:
  sprockets ~> 3.0.0.beta.8

The bundle currently has sprockets locked at 2.12.3.
Try running `bundle update sprockets`
```

I ran  `bundle update sprockets` and `bundle update middleman-sprockets` but no luck and ended up with the terminal spitting out:

```
Bundler could not find compatible versions for gem "sprockets":
  In Gemfile:
    middleman-sprockets (~> 3.1.2) ruby depends on
      sprockets (~> 2.1) ruby

    sprockets (3.0.0.beta.8)
```

I even tried to manuall update the sprockets version in my gemfile.lock to 3.0.0.beta.8 but still no luck.

```
== The Middleman is loading
== Activating: sprockets
== Reading:  Local config
== Activating: livereload
== Activating: relative_assets
== Activating: directory_indexes
/Users/bermonpainter/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.8/lib/sprockets/ejs_processor.rb:1:in `require': cannot load such file -- ejs (LoadError)
	from /Users/bermonpainter/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.8/lib/sprockets/ejs_processor.rb:1:in `<top (required)>'
	from /Users/bermonpainter/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.8/lib/sprockets/ejs_template.rb:1:in `require'
	from /Users/bermonpainter/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.8/lib/sprockets/ejs_template.rb:1:in `<top (required)>'
```

**Comment by tdreyno** [comment]
Because 3.0 is a major version change, we'd have to update `middleman-sprockets` to allow that. A PR against `middleman-sprockets` to bump the dependency to the 3.0 betas will test if the major change breaks our support

**Comment by bpainter** [comment]
@tdreyno Makes sense. I can take a swing at a PR if you want.

**Comment by tdreyno** [comment]
Would love that. Thanks @bpainter

**Comment by leonardoscorza** [comment]
/home/leonardo/.rvm/gems/ruby-2.1.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:153:in `resolve': couldn't find file '/home/leonardo/psdhtml (3)/source/images/background.png' (Sprockets::FileNotFound)

This problem took me a good time :(. The solution was simple, rename the folder psdtohtml (3) for psdtohtml. (No space)

**Comment by stilllife00** [comment]
so what about this error on a fresh middleman installation and no spaces or parenthesis or extension in any folder ?

C:/Users/mirko/www/paridedesign/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/l
ib/sprockets/base.rb:153:in `resolve': couldn't find file 'C:\Users\mirko\www\paridedesign\source\images\backgroundoverlay.jpg' (Sprockets::FileNotFound)

**Comment by tdreyno** [comment]
Please open new tickets for new issues.
