### ISSUE TITLE
Page build breaks if dotfile encountered

### ISSUE THREAD

**Issue by eaigner** [middleman/middleman-sprockets#85]
If I have a `.jshintrc` file in my JS directory. Middleman sprockets crashes with the following stacktrace.

```
../gems/middleman-sprockets-4.0.0.rc.1/lib/middleman-sprockets/extension.rb:235:in `initialize': undefined method `source' for nil:NilClass (NoMethodError)
from ../gems/middleman-sprockets-4.0.0.rc.1/lib/middleman-sprockets/extension.rb:120:in `new'
from ../gems/middleman-sprockets-4.0.0.rc.1/lib/middleman-sprockets/extension.rb:120:in `generate_resource'
from ../gems/middleman-sprockets-4.0.0.rc.1/lib/middleman-sprockets/extension.rb:97:in `block in manipulate_resource_list'
from ../gems/middleman-sprockets-4.0.0.rc.1/lib/middleman-sprockets/extension.rb:90:in `each'
from ../gems/middleman-sprockets-4.0.0.rc.1/lib/middleman-sprockets/extension.rb:90:in `reduce'
from ../gems/middleman-sprockets-4.0.0.rc.1/lib/middleman-sprockets/extension.rb:90:in `manipulate_resource_list'
from ../gems/middleman-core-4.0.0/lib/middleman-core/sitemap/store.rb:206:in `block (2 levels) in ensure_resource_list_updated!'
from ../gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `each'
from ../gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
from ../gems/hamster-2.0.0/lib/hamster/vector.rb:431:in `each'
from ../gems/middleman-core-4.0.0/lib/middleman-core/sitemap/store.rb:204:in `block in ensure_resource_list_updated!'
from ../lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
from ../gems/middleman-core-4.0.0/lib/middleman-core/sitemap/store.rb:196:in `ensure_resource_list_updated!'
from ../gems/middleman-core-4.0.0/lib/middleman-core/sitemap/store.rb:153:in `block in resources'
from ../lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
from ../gems/middleman-core-4.0.0/lib/middleman-core/sitemap/store.rb:152:in `resources'
from ../gems/middleman-core-4.0.0/lib/middleman-core/util.rb:518:in `find_related_files'
from ../gems/middleman-core-4.0.0/lib/middleman-core/sources/source_watcher.rb:237:in `update'
from ../gems/middleman-core-4.0.0/lib/middleman-core/sources/source_watcher.rb:188:in `poll_once!'
from ../gems/middleman-core-4.0.0/lib/middleman-core/sources.rb:129:in `watch'
from ../gems/middleman-core-4.0.0/lib/middleman-core/core_extensions/i18n.rb:48:in `after_configuration'
from ../gems/middleman-core-4.0.0/lib/middleman-core/extension.rb:385:in `block in bind_after_configuration'
from ../gems/middleman-core-4.0.0/lib/middleman-core/callback_manager.rb:51:in `instance_exec'
from ../gems/middleman-core-4.0.0/lib/middleman-core/callback_manager.rb:51:in `block in execute'
from ../gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `each'
from ../gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
from ../gems/hamster-2.0.0/lib/hamster/vector.rb:431:in `each'
from ../gems/middleman-core-4.0.0/lib/middleman-core/callback_manager.rb:51:in `execute'
from ../gems/middleman-core-4.0.0/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
from ../gems/middleman-core-4.0.0/lib/middleman-core/application.rb:289:in `start_lifecycle'
from ../gems/middleman-core-4.0.0/lib/middleman-core/application.rb:265:in `initialize'
from ../gems/middleman-cli-4.0.0/lib/middleman-cli/build.rb:51:in `new'
from ../gems/middleman-cli-4.0.0/lib/middleman-cli/build.rb:51:in `build'
from ../gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
from ../gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
from ../gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
from ../gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
from ../gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
from ../gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
from ../gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
from ../gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
from ../gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
from ../gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
from ../gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
from ../gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
from ../gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
from ../gems/middleman-cli-4.0.0/bin/middleman:23:in `<top (required)>'
from ../bin/middleman:23:in `load'
from ../bin/middleman:23:in `<main>'
from ../bin/ruby_executable_hooks:15:in `eval'
from ../bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by tdreyno** [comment]
Thanks for reporting.

**Comment by stevenosloan** [comment]
@eaigner with #93 merged this should be resolved in master, please re-open and let me know if you continue to see issues.
