### ISSUE TITLE
undefined method `links' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by olliekav** [middleman/middleman-sprockets#98]
I've just updated my gems to the latest Middleman (I was already on v4) and now I'm getting the following when trying to use `activate :sprockets`

```
/Users/olliekav/.rvm/gems/ruby-2.3.0@capra/bundler/gems/middleman-sprockets-9515bcee4c9e/lib/middleman-sprockets/extension.rb:165:in `process_candidate_sprockets_resource': undefined method `links' for nil:NilClass (NoMethodError)
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/bundler/gems/middleman-sprockets-9515bcee4c9e/lib/middleman-sprockets/extension.rb:73:in `block in manipulate_resource_list'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/bundler/gems/middleman-sprockets-9515bcee4c9e/lib/middleman-sprockets/extension.rb:72:in `map'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/bundler/gems/middleman-sprockets-9515bcee4c9e/lib/middleman-sprockets/extension.rb:72:in `manipulate_resource_list'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-core-4.1.3/lib/middleman-core/sitemap/store.rb:234:in `block (4 levels) in ensure_resource_list_updated!'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-core-4.1.3/lib/middleman-core/util.rb:21:in `instrument'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-core-4.1.3/lib/middleman-core/sitemap/store.rb:232:in `block (3 levels) in ensure_resource_list_updated!'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-core-4.1.3/lib/middleman-core/sitemap/store.rb:231:in `block (2 levels) in ensure_resource_list_updated!'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-core-4.1.3/lib/middleman-core/util.rb:21:in `instrument'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-core-4.1.3/lib/middleman-core/sitemap/store.rb:224:in `block in ensure_resource_list_updated!'
	from /Users/olliekav/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-core-4.1.3/lib/middleman-core/sitemap/store.rb:221:in `ensure_resource_list_updated!'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-core-4.1.3/lib/middleman-core/sitemap/extensions/on_disk.rb:21:in `ready'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-core-4.1.3/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-core-4.1.3/lib/middleman-core/callback_manager.rb:57:in `block in execute'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-core-4.1.3/lib/middleman-core/callback_manager.rb:57:in `execute'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-core-4.1.3/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-core-4.1.3/lib/middleman-core/application.rb:297:in `initialize'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-core-4.1.3/lib/middleman-core/preview_server.rb:142:in `new'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-core-4.1.3/lib/middleman-core/preview_server.rb:142:in `initialize_new_app'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-core-4.1.3/lib/middleman-core/preview_server.rb:34:in `start'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-cli-4.1.3/lib/middleman-cli/server.rb:53:in `server'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/gems/middleman-cli-4.1.3/bin/middleman:66:in `<top (required)>'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/bin/middleman:23:in `load'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/bin/middleman:23:in `<main>'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/bin/ruby_executable_hooks:15:in `eval'
	from /Users/olliekav/.rvm/gems/ruby-2.3.0@capra/bin/ruby_executable_hooks:15:in `<main>'
```

Gemfile
```
# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

gem 'middleman', '~> 4.1', '>= 4.1.3'
gem "turbolinks", github: 'rails/turbolinks', branch: 'master', :require => false
gem "middleman-sprockets", github: "middleman/middleman-sprockets"
gem 'middleman-livereload'
gem "middleman-syntax", github: 'thisiscapra/middleman-syntax', branch: 'master'
gem "contentful_middleman", github: 'contentful/contentful_middleman', branch: 'dl/upgrade-to-v4'
gem "nokogiri"
gem "redcarpet"
gem 'therubyracer'
gem 'oj'
```

Any ideas? Is it something thats changed in the latest Middleman Core or Middleman Sprockets?

**Comment by tdreyno** [comment]
Middleman Sprockets has been evolving quickly these last few weeks. I'll let @stevenosloan chime in if he has a lead.

**Comment by stevenosloan** [comment]
Yeah this is definitely middleman-sprockets -- I think coming from me deferring rendering/error handling. I'll have some time to dig in a bit more later today.

**Comment by stevenosloan** [comment]
Hey @olliekav I've added some debugging output, you mind running from master and posting the `Sprockets Debug: ...` lines? It looks like there's assets being marked as processable, but then the set sprockets_path isn't found in the sprockets lookup paths. The debug lines should give us some insight into what the asset is, and how we're telling sprockets to find it.

**Comment by olliekav** [comment]
@stevenosloan Sure, I'll do this today. Thanks!

**Comment by olliekav** [comment]
Hey @stevenosloan, apologies for the delay getting this back to you. Output below...

```
== Sprockets Debug: #<Middleman::Sitemap::Resource path=fonts/263905/027807B1003227F6A.css>
== Sprockets Debug: #<Middleman::SprocketsExtension::SprocketsResource path=fonts/263905/027807B1003227F6A.css>
```
So it looks like a problem with the fonts from typography.com, it's self hosting and I had original issues with them in the build so I ignore them and add them back in after_build (see below). 

```
# Build-specific configuration
configure :build do
  
  # Minify CSS on build
  activate :minify_css

  # Minify Javascript on build
  activate :minify_javascript

  # Enable cache buster
  activate :asset_hash

  activate :gzip

  # Use relative URLs
  # activate :relative_assets
  
  # Fix bug with build errors and typography fonts
  ignore 'fonts/*'

  after_build do |builder|
    print "After_build fixes... "
    FileUtils.cp_r(Dir['source/fonts/'],'build/')
    puts "done."
  end
  
end
```

I'm guessing it may be something to do with that `after_build` method?

**Comment by stevenosloan** [comment]
Awesome, thanks @olliekav -- I think I can see what's happening. Looks like I might have goofed when I allowed sprockets to handle assets outside of css_dir or js_dir. It'll take me a little bit to get a fix up, but I *think* adding source to your sprockets path should work for you in the meantime.

```ruby
activate :sprockets
sprockets.append_path File.join( root, 'source' )
```

**Comment by olliekav** [comment]
@stevenosloan Yep, that's working for me. Thanks for being so prompt looking into it. Much appreciated!

**Comment by stevenosloan** [comment]
@olliekav should be good on master now, thanks for the report.
